import Head from 'next/head'
import Image from 'next/image'
import { BiUpload } from 'react-icons/bi'
import Navbar from '../components/Navbar'
import Upload from '../components/Upload'
import { useState } from 'react'
import Images from '../components/Images'

export default function Home({uploadClicked, images}) {
 
  return (
    <div>
      <Head>
        <title>Dobby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {
      uploadClicked && <Upload/>
    }
    <Images images={images}/>
    </div>
  )
}
